version: '3.8'

services:
  be:
    image: 'docker-spring-boot-postgres:latest'
    container_name: pm-be
    build: ./src-be/
    ports:
      - 8080:8081
    restart: on-failure
    volumes:
      - .m2:/root/.m2

  fe:
    container_name: pm-fe
    build:
      context: src-fe
      target: development
    volumes:
      - ./src-fe/src:/app/fe/src
      - /project/node_modules
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - be
